version: '3.7'
services:
  golang:
    build:
      context: .
      dockerfile: ./dockerfiles/golang/Dockerfile
    volumes:
    - .:/go/src/github.com/endotakuya/grpc-example:cached
    depends_on:
    - db
    ports:
    - "50051:50051"
    tty: yes
  node:
    build:
      context: .
      dockerfile: ./dockerfiles/node/Dockerfile
    environment:
      SERVER_HOST: golang
    volumes:
    - ./front:/front:cached
    - ./article:/article:cached
    ports:
    - "3000:3000"
    tty: yes
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: grpc_example
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
    - "3306:3306"
    volumes:
    - data:/var/lib/mysql
volumes:
  data:
